/**
 * utils/pdfGenerator.js
 * Generates a PDF attendance sheet using PDFKit.
 * Streams the PDF directly to the Express response object.
 */

const PDFDocument = require("pdfkit");

/**
 * @param {Object} sessionData
 * @param {import('express').Response} res - Express response (writable stream)
 */
function generateSessionPDF(sessionData, res) {
  const doc = new PDFDocument({ margin: 50, size: "A4" });

  doc.pipe(res);

  // ─── Header ──────────────────────────────────────────────────────────────
  doc
    .rect(0, 0, doc.page.width, 80)
    .fill("#0B0E1A");

  doc
    .fillColor("#00E5B3")
    .fontSize(24)
    .font("Helvetica-Bold")
    .text("ChainPresence", 50, 20, { align: "left" });

  doc
    .fillColor("#F0F2FF")
    .fontSize(12)
    .font("Helvetica")
    .text("Decentralized Attendance Record", 50, 50, { align: "left" });

  doc.moveDown(2);

  // ─── Session Details ──────────────────────────────────────────────────────
  doc.fillColor("#0B0E1A");

  const openedDate  = new Date(sessionData.openedAt * 1000).toLocaleString();
  const closedDate  = sessionData.closedAt
    ? new Date(sessionData.closedAt * 1000).toLocaleString()
    : "Still Open";

  doc
    .fontSize(18)
    .font("Helvetica-Bold")
    .fillColor("#131826")
    .text(sessionData.courseName, { align: "center" });

  doc.moveDown(0.5);

  const details = [
    ["Course ID",   sessionData.courseId],
    ["Session ID",  String(sessionData.id)],
    ["Professor",   sessionData.professor],
    ["Opened At",   openedDate],
    ["Closed At",   closedDate],
    ["Duration",    `${sessionData.duration} minutes`],
    ["Total Attendees", String(sessionData.attendees.length)],
  ];

  doc.fontSize(11).font("Helvetica");

  details.forEach(([label, value]) => {
    doc
      .fillColor("#7A7F9A")
      .text(`${label}: `, { continued: true })
      .fillColor("#0B0E1A")
      .text(value);
  });

  doc.moveDown(1.5);

  // ─── Attendee Table ───────────────────────────────────────────────────────
  doc
    .fontSize(14)
    .font("Helvetica-Bold")
    .fillColor("#0B0E1A")
    .text("Attendance List");

  doc.moveDown(0.5);

  // Table header
  const colX   = { name: 50, wallet: 200, status: 430 };
  const rowH   = 25;
  const startY = doc.y;

  doc
    .rect(50, startY, doc.page.width - 100, rowH)
    .fill("#0B0E1A");

  doc
    .fillColor("#00E5B3")
    .fontSize(10)
    .font("Helvetica-Bold");

  doc.text("#",        55,  startY + 8, { width: 30 });
  doc.text("Name",     colX.name + 20, startY + 8, { width: 140 });
  doc.text("Wallet",   colX.wallet,    startY + 8, { width: 220 });
  doc.text("Status",   colX.status,    startY + 8, { width: 60 });

  let y = startY + rowH;

  sessionData.attendees.forEach((attendee, i) => {
    const bg = i % 2 === 0 ? "#F7F9FF" : "#ECEEF8";
    doc.rect(50, y, doc.page.width - 100, rowH).fill(bg);

    doc
      .fillColor("#0B0E1A")
      .fontSize(9)
      .font("Helvetica");

    doc.text(String(i + 1),           55,             y + 8, { width: 30 });
    doc.text(attendee.name || "—",    colX.name + 20, y + 8, { width: 140 });
    doc.text(attendee.address,        colX.wallet,    y + 8, { width: 220, ellipsis: true });
    doc.fillColor("#00C49A").text("✓ Present",        colX.status, y + 8, { width: 70 });

    y += rowH;

    if (y > doc.page.height - 80) {
      doc.addPage();
      y = 50;
    }
  });

  // ─── Footer ───────────────────────────────────────────────────────────────
  doc.moveDown(2);
  doc
    .fontSize(8)
    .fillColor("#7A7F9A")
    .text(
      `Generated by ChainPresence on ${new Date().toLocaleString()} | Blockchain-verified attendance`,
      { align: "center" }
    );

  doc.end();
}

module.exports = { generateSessionPDF };
